In [13]:
import pandas as pd
import glob
files = glob.glob('envirocar_tracks_csv/*.csv')
# https://medium.com/@itylergarrett.tag/find-and-replace-in-a-csv-using-python-f983f950acfb
for file in files:
    print(file)
    text = open(file, 'r')
    text = ''.join([i for i in text]).replace(";", ",")
    x = open(file, 'w')
    x.writelines(text)
    x.close()  

# df = pd.read_csv('envirocar_tracks_csv/5a2c14ea268d1b08cd0c1e79.csv')
# df

envirocar_tracks_csv/51c97d05e4b0fe5a04e9e733.csv
envirocar_tracks_csv/51c980c8e4b05956bbffcefd.csv
envirocar_tracks_csv/51c9bb64e4b0fe5a04eaba9c.csv
envirocar_tracks_csv/51cae00ce4b0a34fb6c5d7f9.csv
envirocar_tracks_csv/51cc0e80e4b0f7630818e1ac.csv
envirocar_tracks_csv/51cc0e88e4b0f7630818e1d7.csv
envirocar_tracks_csv/51cc0eaae4b0f7630818e22c.csv
envirocar_tracks_csv/51cc0ed2e4b0f7630818e373.csv
envirocar_tracks_csv/51cda9a3e4b0f7630819472b.csv
envirocar_tracks_csv/51cda9a5e4b0f76308194880.csv
envirocar_tracks_csv/51d0ab7ce4b0f763081a2e92.csv
envirocar_tracks_csv/51d0ab7de4b0f763081a2e97.csv
envirocar_tracks_csv/51d0ab7de4b0f763081a2ea4.csv
envirocar_tracks_csv/51d0ab7de4b0f763081a2ea9.csv
envirocar_tracks_csv/51d333e1e4b01cbb274b6e8a.csv
envirocar_tracks_csv/51d333f0e4b01cbb274b726b.csv
envirocar_tracks_csv/51d45fd1e4b04fe4d7650148.csv
envirocar_tracks_csv/51d46f8ce4b04fe4d7653a11.csv
envirocar_tracks_csv/51d46f8ee4b04fe4d7653adc.csv
envirocar_tracks_csv/51d46f91e4b04fe4d7653ef7.csv
envirocar_tracks_csv/51d6de3de4b0798b041df58f.csv
envirocar_tracks_csv/51d6fbf0e4b0798b041e26d2.csv
envirocar_tracks_csv/51d6ff38e4b0798b041e3862.csv
envirocar_tracks_csv/51d9bf20e4b0798b041efdf8.csv
envirocar_tracks_csv/51d9c2cce4b0798b041f006e.csv
envirocar_tracks_csv/51d9c520e4b0798b041f1d87.csv
envirocar_tracks_csv/51d9d092e4b0798b041f1e32.csv
envirocar_tracks_csv/51d9d41ae4b0798b041f1f03.csv
envirocar_tracks_csv/51d9d5dee4b0798b041f3712.csv
envirocar_tracks_csv/51d9d70ae4b0798b041f37db.csv
envirocar_tracks_csv/51d9d8bbe4b0798b041f3e68.csv
envirocar_tracks_csv/51d9dc71e4b0798b041f50c3.csv
envirocar_tracks_csv/51dbfb5de4b0743c0890ee89.csv
envirocar_tracks_csv/51dc2a2be4b0a504afb7b8c3.csv
envirocar_tracks_csv/51dcfb5ee4b0a504afb7c182.csv
envirocar_tracks_csv/51df00d7e4b0a504afb87b1f.csv
envirocar_tracks_csv/51dfde52e4b0feb05dbecb54.csv
envirocar_tracks_csv/51dfec72e4b0feb05dbede3d.csv
envirocar_tracks_csv/51dfed3ce4b0feb05dbede76.csv
envirocar_tracks_csv/51dfee07e4b0feb05dbedf0b.csv
envirocar_tracks_csv/51dfeed9e4b0feb05dbedf68.csv
envirocar_tracks_csv/51dfefa1e4b0feb05dbedfbf.csv
envirocar_tracks_csv/51dff0a1e4b0feb05dbee00e.csv
envirocar_tracks_csv/51dff239e4b0feb05dbee0d7.csv
envirocar_tracks_csv/51e44857e4b0feb05dbf4d4d.csv
envirocar_tracks_csv/51e4485ee4b0feb05dbf4edb.csv
envirocar_tracks_csv/51e59d42e4b058cd3d39ba45.csv
envirocar_tracks_csv/51e6d3fee4b058cd3d3a2d5b.csv
envirocar_tracks_csv/51e97df6e4b058cd3d3a75a9.csv
envirocar_tracks_csv/51eec431e4b058cd3d5af06b.csv
envirocar_tracks_csv/51efeb85e4b058cd3d5b0852.csv
envirocar_tracks_csv/51f67058e4b058cd3d62f340.csv
envirocar_tracks_csv/52073ba0e4b058cd3d6641c4.csv
envirocar_tracks_csv/5207d868e4b058cd3d66983f.csv
envirocar_tracks_csv/5207d871e4b058cd3d669afe.csv
envirocar_tracks_csv/520921eee4b058cd3d672dda.csv
envirocar_tracks_csv/520a795de4b058cd3d683940.csv
envirocar_tracks_csv/52131c9ce4b00a043c407a30.csv
envirocar_tracks_csv/5213854be4b00a043c40a49b.csv
envirocar_tracks_csv/521740cbe4b00a043c416017.csv
envirocar_tracks_csv/521740cde4b00a043c416222.csv
envirocar_tracks_csv/5218fe29e4b00a043c41b5be.csv
envirocar_tracks_csv/5218fe2ce4b00a043c41ba89.csv
envirocar_tracks_csv/52198c30e4b00a043c41e567.csv
envirocar_tracks_csv/5219940ce4b00a043c41e84a.csv
envirocar_tracks_csv/521ba0dfe4b00a043c41fb2c.csv
envirocar_tracks_csv/521ba5aae4b00a043c41fe3b.csv
envirocar_tracks_csv/521c8a7fe4b00a043c4202e4.csv
envirocar_tracks_csv/521c8a91e4b00a043c42057b.csv
envirocar_tracks_csv/521cd816e4b00a043c4210ef.csv
envirocar_tracks_csv/521e1e8ee4b00a043c421784.csv
envirocar_tracks_csv/521e3598e4b00a043c421cb3.csv
envirocar_tracks_csv/52264435e4b00a043c437013.csv
envirocar_tracks_csv/5226443ce4b00a043c4372b6.csv
envirocar_tracks_csv/52264443e4b00a043c4374f9.csv
envirocar_tracks_csv/52264446e4b00a043c4376f8.csv
envirocar_tracks_csv/522d9877e4b00a043c46b236.csv
envirocar_tracks_csv/52381c9fe4b060b8865a5e25.csv
envirocar_tracks_csv/523c7055e4b060b8865cba40.csv
envirocar_tracks_csv/523c705ae4b060b8865cbf7b.csv
envirocar_tracks_csv/5241ce39e4b0d7bdddd6d47f.csv
envirocar_tracks_csv/524945fee4b04f4d08ec3bad.csv
envirocar_tracks_csv/52529d62e4b04f4d08f0fe70.csv
envirocar_tracks_csv/52529d64e4b04f4d08f10077.csv
envirocar_tracks_csv/525e3e7be4b000fe057e6fb3.csv
envirocar_tracks_csv/525e3e7de4b000fe057e748a.csv
envirocar_tracks_csv/525e3e7fe4b000fe057e773d.csv
envirocar_tracks_csv/525e3e83e4b000fe057e7eab.csv
envirocar_tracks_csv/525e3e85e4b000fe057e856e.csv
envirocar_tracks_csv/525e3e86e4b000fe057e8ae0.csv
envirocar_tracks_csv/525e3e88e4b000fe057e8cba.csv
envirocar_tracks_csv/525fc975e4b000fe05800e0d.csv
envirocar_tracks_csv/5260d16de4b000fe05802b2e.csv
envirocar_tracks_csv/52624a53e4b000fe05806ea1.csv
envirocar_tracks_csv/52696cbbe4b000fe058173ae.csv
envirocar_tracks_csv/526d7d10e4b000fe05821848.csv
envirocar_tracks_csv/526d7d12e4b000fe05821bbf.csv
envirocar_tracks_csv/526d7d14e4b000fe05821d63.csv
envirocar_tracks_csv/526d7d15e4b000fe05821d8c.csv
envirocar_tracks_csv/526fc184e4b05a86b117aa1b.csv
envirocar_tracks_csv/526fc184e4b05a86b117aa7b.csv
envirocar_tracks_csv/526fc185e4b05a86b117aaf3.csv
envirocar_tracks_csv/526fc18ae4b05a86b117ab5a.csv
envirocar_tracks_csv/526fc195e4b05a86b117aec0.csv
envirocar_tracks_csv/52758ab3e4b000fe05830933.csv
envirocar_tracks_csv/527769cde4b0474db1b86443.csv
envirocar_tracks_csv/5277b0a1e4b01edb6ad7957d.csv
envirocar_tracks_csv/527bc3a3e4b08cecc597d269.csv
envirocar_tracks_csv/527bc3a5e4b08cecc597d4e8.csv
envirocar_tracks_csv/52810d8be4b08cecc59a56b4.csv
envirocar_tracks_csv/52810d8fe4b08cecc59a5907.csv
envirocar_tracks_csv/52812123e4b08cecc59a6234.csv
envirocar_tracks_csv/52812123e4b08cecc59a6297.csv
envirocar_tracks_csv/528349ade4b08cecc5a0a0b8.csv
envirocar_tracks_csv/528349bee4b08cecc5a0b98d.csv
envirocar_tracks_csv/52881881e4b08cecc5a3963d.csv
envirocar_tracks_csv/528bd89ce4b08cecc5a6d458.csv
envirocar_tracks_csv/528bd8a2e4b08cecc5a6f321.csv
envirocar_tracks_csv/528bd8b1e4b08cecc5a6f8bc.csv
envirocar_tracks_csv/528cf184e4b0a727145dd563.csv
envirocar_tracks_csv/528cf1a3e4b0a727145df093.csv
envirocar_tracks_csv/528f1a16e4b0ca505ba92f41.csv
envirocar_tracks_csv/528f1a19e4b0ca505ba93418.csv
envirocar_tracks_csv/528f1a20e4b0ca505ba93efc.csv
envirocar_tracks_csv/528f1a23e4b0ca505ba943d3.csv
envirocar_tracks_csv/52af4fd0e4b0593cce13bebc.csv
envirocar_tracks_csv/52af4fd3e4b0593cce13bfc7.csv
envirocar_tracks_csv/52af4fe1e4b0593cce13cc37.csv
envirocar_tracks_csv/52af4fe4e4b0593cce13ccc6.csv
envirocar_tracks_csv/52af4fe9e4b0593cce13cf5d.csv
envirocar_tracks_csv/52b19f7ae4b0f9afbd14d3a0.csv
envirocar_tracks_csv/52b19f7ce4b0f9afbd14d773.csv
envirocar_tracks_csv/52b1d884e4b0f9afbd163bc7.csv
envirocar_tracks_csv/52b477a8e4b0f9afbd2cddc7.csv
envirocar_tracks_csv/52b477aee4b0f9afbd2ce014.csv
envirocar_tracks_csv/52caf543e4b0f9afbd8d7f8c.csv
envirocar_tracks_csv/52de295be4b0d8e8c1fcbac9.csv
envirocar_tracks_csv/52de295ee4b0d8e8c1fcbd1c.csv
envirocar_tracks_csv/52de2964e4b0d8e8c1fcc256.csv
envirocar_tracks_csv/52e39b02e4b0d8e8c22665c3.csv
envirocar_tracks_csv/52eabd02e4b0d8e8c250ca6d.csv
envirocar_tracks_csv/52ebdd3ce4b0d8e8c255fe6f.csv
envirocar_tracks_csv/52ebdd42e4b0d8e8c25601a2.csv
envirocar_tracks_csv/52ebdd53e4b0d8e8c2561aed.csv
envirocar_tracks_csv/52ebf0b6e4b0d8e8c2564217.csv
envirocar_tracks_csv/52f3836be4b0d8e8c27ed6f0.csv
envirocar_tracks_csv/52f3836de4b0d8e8c27ed83b.csv
envirocar_tracks_csv/52f38373e4b0d8e8c27edee7.csv
envirocar_tracks_csv/52f47942e4b0d8e8c286f6cf.csv
envirocar_tracks_csv/52f6c62de4b0d8e8c28df6a2.csv
envirocar_tracks_csv/530f2d96e4b0b84b4666e63a.csv
envirocar_tracks_csv/5315fb3ae4b0b84b46a3db93.csv
envirocar_tracks_csv/5315fb42e4b0b84b46a3deaa.csv
envirocar_tracks_csv/531720f7e4b0b84b46b3451d.csv
envirocar_tracks_csv/5318d766e4b0b84b46ec51d9.csv
envirocar_tracks_csv/53218b43e4b0c917fe59aa8f.csv
envirocar_tracks_csv/5326e546e4b09d7b3354ed3a.csv
envirocar_tracks_csv/5330703ce4b09d7b33eaa0c3.csv
envirocar_tracks_csv/53341a4ae4b09d7b342b20b3.csv
envirocar_tracks_csv/53341a4ce4b09d7b342b21ae.csv
envirocar_tracks_csv/5346d1d9e4b09d7b34fc0d27.csv
envirocar_tracks_csv/53579ffce4b0976b09b91b09.csv
envirocar_tracks_csv/5357a002e4b0976b09b935d0.csv
envirocar_tracks_csv/535e0896e4b0976b09bda210.csv
envirocar_tracks_csv/535e0898e4b0976b09bda467.csv
envirocar_tracks_csv/5360edfbe4b0976b09c0a496.csv
envirocar_tracks_csv/536a5899e4b05e62154cdc3d.csv
envirocar_tracks_csv/536a589ce4b05e62154cde58.csv
envirocar_tracks_csv/536c717ee4b05e62154d6a68.csv
envirocar_tracks_csv/53711092e4b05e62154e970e.csv
envirocar_tracks_csv/537110a9e4b05e62154ef772.csv
envirocar_tracks_csv/537110b3e4b05e62154ef8df.csv
envirocar_tracks_csv/537110c6e4b05e62154efae9.csv
envirocar_tracks_csv/5371e96ce4b05e62154ff5ad.csv
envirocar_tracks_csv/5371e972e4b05e62155002c4.csv
envirocar_tracks_csv/5375a7fee4b008867f76eec9.csv
envirocar_tracks_csv/5375a80ee4b008867f76f090.csv
envirocar_tracks_csv/5375a81ae4b008867f76f736.csv
envirocar_tracks_csv/537a6a46e4b008867f7d4dc3.csv
envirocar_tracks_csv/537a6a65e4b008867f7d521e.csv
envirocar_tracks_csv/537a6a71e4b008867f7d6231.csv
envirocar_tracks_csv/537e283ae4b008867f7e901f.csv
envirocar_tracks_csv/537e2a7fe4b008867f7ea459.csv
envirocar_tracks_csv/5383ab13e4b008867f84c2b1.csv
envirocar_tracks_csv/5383ab17e4b008867f84c5e8.csv
envirocar_tracks_csv/53a455b7e4b01607fa4b86ab.csv
envirocar_tracks_csv/53b257d1e4b01607fa534632.csv
envirocar_tracks_csv/53b257e6e4b01607fa534859.csv
envirocar_tracks_csv/53b27449e4b01607fa53736d.csv
envirocar_tracks_csv/53b27494e4b01607fa538d1d.csv
envirocar_tracks_csv/53b2cd6ae4b01607fa54417c.csv
envirocar_tracks_csv/53b2cd7de4b01607fa544927.csv
envirocar_tracks_csv/53b2cd91e4b01607fa544f12.csv
envirocar_tracks_csv/53b2cda1e4b01607fa5454e1.csv
envirocar_tracks_csv/53b3b066e4b01607fa54ed80.csv
envirocar_tracks_csv/53b3b0cde4b01607fa552940.csv
envirocar_tracks_csv/53b3b0d6e4b01607fa554637.csv
envirocar_tracks_csv/53b3b0dee4b01607fa556250.csv
envirocar_tracks_csv/53b3b0e8e4b01607fa5575d5.csv
envirocar_tracks_csv/53b3b0f0e4b01607fa558784.csv
envirocar_tracks_csv/53b3b0f8e4b01607fa5591f5.csv
envirocar_tracks_csv/53b514bee4b01607fa560ce2.csv
envirocar_tracks_csv/53b52266e4b01607fa5656d3.csv
envirocar_tracks_csv/53b52277e4b01607fa565fa6.csv
envirocar_tracks_csv/53b52282e4b01607fa566469.csv
envirocar_tracks_csv/53b5228ee4b01607fa566b78.csv
envirocar_tracks_csv/53f3dde0e4b0d0547766b9cb.csv
envirocar_tracks_csv/53f3dde7e4b0d0547766d5b2.csv
envirocar_tracks_csv/53f3de14e4b0d0547767004b.csv
envirocar_tracks_csv/53f3de18e4b0d0547767017a.csv
envirocar_tracks_csv/53f8c09ee4b04c314e7ce34c.csv
envirocar_tracks_csv/53f8c0a5e4b04c314e7ce56b.csv
envirocar_tracks_csv/53f8c0aae4b04c314e7ced82.csv
envirocar_tracks_csv/53fb5fa2e4b04c314e7f4265.csv
envirocar_tracks_csv/53fb60ede4b04c314e8083f9.csv
envirocar_tracks_csv/54001c3ee4b04c314e92133e.csv
envirocar_tracks_csv/54168ba2e4b015877e69f69b.csv
envirocar_tracks_csv/5434fd67e4b015877e9d5730.csv
envirocar_tracks_csv/545a1e8fe4b0b53890a2c1f3.csv
envirocar_tracks_csv/545a6a6fe4b0b53890a2d10f.csv
envirocar_tracks_csv/54671702e4b094bfc4da43f6.csv
envirocar_tracks_csv/546729a0e4b094bfc4da4f86.csv
envirocar_tracks_csv/546b58dce4b094c102d8218a.csv
envirocar_tracks_csv/54706aa8e4b094c1030086ea.csv
envirocar_tracks_csv/5479fc13e4b094c1032a7c5b.csv
envirocar_tracks_csv/5479fc1ae4b094c1032a7d32.csv
envirocar_tracks_csv/5479fc1ce4b094c1032a7f19.csv
envirocar_tracks_csv/54b17139e4b08a7098cc275b.csv
envirocar_tracks_csv/54b57599e4b08a7098d0b0ca.csv
envirocar_tracks_csv/54b5759fe4b08a7098d0b541.csv
envirocar_tracks_csv/54b575aae4b08a7098d0baf6.csv
envirocar_tracks_csv/54c901f9e4b0887704ec87b3.csv
envirocar_tracks_csv/54c90200e4b0887704ec9334.csv
envirocar_tracks_csv/54e30a82e4b0558690c54556.csv
envirocar_tracks_csv/54e30acce4b0558690c54ba8.csv
envirocar_tracks_csv/54e30acfe4b0558690c54e87.csv
envirocar_tracks_csv/54e30adbe4b0558690c54e8e.csv
envirocar_tracks_csv/54ea49a1e4b0558690c7db0a.csv
envirocar_tracks_csv/54ec23d1e4b0558690c83b00.csv
envirocar_tracks_csv/54ec23d6e4b0558690c83df7.csv
envirocar_tracks_csv/54ec256fe4b0558690c891bc.csv
envirocar_tracks_csv/54ec2575e4b0558690c894b3.csv
envirocar_tracks_csv/54ec2acce4b0558690c8e671.csv
envirocar_tracks_csv/54ec2ad2e4b0558690c8e968.csv
envirocar_tracks_csv/54ec2f18e4b0558690c93703.csv
envirocar_tracks_csv/54ec2f1ee4b0558690c939fa.csv
envirocar_tracks_csv/54ec3350e4b0558690c9809a.csv
envirocar_tracks_csv/54f796ace4b0bf5f3ce0b110.csv
envirocar_tracks_csv/54f7978be4b0bf5f3ce105a1.csv
envirocar_tracks_csv/54f7984ae4b0bf5f3ce1673d.csv
envirocar_tracks_csv/54f79914e4b0bf5f3ce1c8d9.csv
envirocar_tracks_csv/54f79adbe4b0bf5f3ce22d55.csv
envirocar_tracks_csv/54f79c64e4b0bf5f3ce2ab04.csv
envirocar_tracks_csv/54f79d9ee4b0bf5f3ce30ca0.csv
envirocar_tracks_csv/54f79ecbe4b0bf5f3ce36e3c.csv
envirocar_tracks_csv/54f79fe6e4b0bf5f3ce3cfd8.csv
envirocar_tracks_csv/54f7a079e4b0bf5f3ce43174.csv
envirocar_tracks_csv/54fc484de4b0bf5f3ceb097c.csv
envirocar_tracks_csv/54fc4853e4b0bf5f3ceb0ad3.csv
envirocar_tracks_csv/54fda585e4b0bf5f3cf0ce0a.csv
envirocar_tracks_csv/54fda589e4b0bf5f3cf0d0f9.csv
envirocar_tracks_csv/54fda58ae4b0bf5f3cf0d400.csv
envirocar_tracks_csv/55080c7ee4b0bf5f3d061868.csv
envirocar_tracks_csv/55080c87e4b0bf5f3d061b07.csv
envirocar_tracks_csv/550ab4aae4b0bf5f3d0ee152.csv
envirocar_tracks_csv/550ab4e9e4b0bf5f3d0f18c0.csv
envirocar_tracks_csv/550ab4fbe4b0bf5f3d0f340f.csv
envirocar_tracks_csv/550ab576e4b0bf5f3d0f4f5e.csv
envirocar_tracks_csv/550ab5e2e4b0bf5f3d0f6aad.csv
envirocar_tracks_csv/550ab607e4b0bf5f3d0f85fc.csv
envirocar_tracks_csv/550ab61fe4b0bf5f3d0fa14b.csv
envirocar_tracks_csv/550ab633e4b0bf5f3d0fbc9a.csv
envirocar_tracks_csv/550ab70fe4b0bf5f3d0fd7e9.csv
envirocar_tracks_csv/550ab786e4b0bf5f3d0ff338.csv
envirocar_tracks_csv/550d8939e4b0bf5f3d150076.csv
envirocar_tracks_csv/550d8955e4b0bf5f3d151f95.csv
envirocar_tracks_csv/550d896fe4b0bf5f3d153eb4.csv
envirocar_tracks_csv/550d8986e4b0bf5f3d155dd3.csv
envirocar_tracks_csv/550d899ee4b0bf5f3d157cf2.csv
envirocar_tracks_csv/550d89b6e4b0bf5f3d159c11.csv
envirocar_tracks_csv/550d89d2e4b0bf5f3d15bb30.csv
envirocar_tracks_csv/551003e6e4b0bf5f3d17f49f.csv
envirocar_tracks_csv/551003e8e4b0bf5f3d17f572.csv
envirocar_tracks_csv/55241838e4b0bf5f3e437753.csv
envirocar_tracks_csv/55241876e4b0bf5f3e43a4aa.csv
envirocar_tracks_csv/552418ace4b0bf5f3e43d3ad.csv
envirocar_tracks_csv/552bff31e4b0bf5f3e46d3fc.csv
envirocar_tracks_csv/552bff35e4b0bf5f3e46d683.csv
envirocar_tracks_csv/553aa4b2e4b080c76377917f.csv
envirocar_tracks_csv/553aa4b9e4b080c763779442.csv
envirocar_tracks_csv/553aa4e9e4b080c763779eda.csv
envirocar_tracks_csv/553aa525e4b080c76377a19d.csv
envirocar_tracks_csv/554ce07de4b048885ee0dfa7.csv
envirocar_tracks_csv/559f7f2fe4b07207d897b8c6.csv
envirocar_tracks_csv/559fd2ace4b07207d8980515.csv
envirocar_tracks_csv/55b005ffe4b0a706113f3372.csv
envirocar_tracks_csv/55b22856e4b0a7061140a288.csv
envirocar_tracks_csv/55c3b74ce4b0a706115b0ee8.csv
envirocar_tracks_csv/55c59096e4b05d8a884b8546.csv
envirocar_tracks_csv/55d470a8e4b05e8195ac08c4.csv
envirocar_tracks_csv/55d5f753e4b05e8195ac72f5.csv
envirocar_tracks_csv/55d5f77fe4b05e8195ac742c.csv
envirocar_tracks_csv/55d5f798e4b05e8195ac7791.csv
envirocar_tracks_csv/55d5f7b8e4b05e8195ac78c8.csv
envirocar_tracks_csv/55d5f7dbe4b05e8195ac7c2b.csv
envirocar_tracks_csv/55d5f7fee4b05e8195ac7d62.csv
envirocar_tracks_csv/55df1aede4b0b51118fa567e.csv
envirocar_tracks_csv/55df1af7e4b0b51118fa5895.csv
envirocar_tracks_csv/55f6951ce4b0a071dd8b487e.csv
envirocar_tracks_csv/5604e9f5e4b0a071dd90c4da.csv
envirocar_tracks_csv/56056902e4b0a071dd90fd71.csv
envirocar_tracks_csv/560bb4e3e4b060377726fcd5.csv
envirocar_tracks_csv/560bb741e4b037cfadf1aab4.csv
envirocar_tracks_csv/560eb5dee4b0a6b8ecb24dac.csv
envirocar_tracks_csv/560eb5f4e4b0a6b8ecb254c5.csv
envirocar_tracks_csv/560eb5ffe4b0a6b8ecb2576f.csv
envirocar_tracks_csv/560eb605e4b0a6b8ecb2585a.csv
envirocar_tracks_csv/561e327be4b0ea4c36924bba.csv
envirocar_tracks_csv/561e87b5e4b0ea4c36926c33.csv
envirocar_tracks_csv/561e9142e4b0ea4c36928256.csv
envirocar_tracks_csv/561f5763e4b0ea4c369299bd.csv
envirocar_tracks_csv/5620a9d4e4b0ea4c36940859.csv
envirocar_tracks_csv/562149dce4b0ea4c36940c2c.csv
envirocar_tracks_csv/56274880e4b0f32e8adcde27.csv
envirocar_tracks_csv/56274890e4b0f32e8adce07f.csv
envirocar_tracks_csv/5627ca1ee4b0f32e8add0e91.csv
envirocar_tracks_csv/5628a6b8e4b0f32e8add3374.csv
envirocar_tracks_csv/562f9e3fe4b0f32e8ade820b.csv
envirocar_tracks_csv/562fe8d6e4b0f32e8ade85a5.csv
envirocar_tracks_csv/562fe90ae4b0f32e8ade8942.csv
envirocar_tracks_csv/564094cfe4b07c4512188cc1.csv
envirocar_tracks_csv/5640a21ce4b07c4512188f6f.csv
envirocar_tracks_csv/5640a228e4b07c451218923e.csv
envirocar_tracks_csv/5640a241e4b07c4512189479.csv
envirocar_tracks_csv/56447223e4b027549291b2f3.csv
envirocar_tracks_csv/5649f8d8e4b027549291ff67.csv
envirocar_tracks_csv/5649f8dfe4b027549292017e.csv
envirocar_tracks_csv/5649f8f9e4b0275492920f7d.csv
envirocar_tracks_csv/5649f912e4b02754929217f1.csv
envirocar_tracks_csv/567aa2a8e4b000f94d91c72d.csv
envirocar_tracks_csv/567aa2aae4b000f94d91c830.csv
envirocar_tracks_csv/567aa2cfe4b000f94d91c837.csv
envirocar_tracks_csv/5693b8a8e4b000f94da2626d.csv
envirocar_tracks_csv/5693b8c9e4b000f94da2639f.csv
envirocar_tracks_csv/5693d8a8e4b000f94da2767f.csv
envirocar_tracks_csv/5693e3b7e4b000f94da27e1f.csv
envirocar_tracks_csv/5694c493e4b000f94da66783.csv
envirocar_tracks_csv/569635c2e4b000f94da7f89c.csv
envirocar_tracks_csv/569635cae4b000f94da7fa8f.csv
envirocar_tracks_csv/569635d1e4b000f94da7fc7c.csv
envirocar_tracks_csv/569635d6e4b000f94da7ff63.csv
envirocar_tracks_csv/56a781bbe4b000f94dbb91d0.csv
envirocar_tracks_csv/56a87695e4b000f94dbbc0d5.csv
envirocar_tracks_csv/56a9517ce4b000f94dbc8d68.csv
envirocar_tracks_csv/56a951a9e4b000f94dbc8f5a.csv
envirocar_tracks_csv/56a95249e4b000f94dbc9584.csv
envirocar_tracks_csv/56a9526fe4b000f94dbc98d8.csv
envirocar_tracks_csv/56aba010e4b058e549400c7b.csv
envirocar_tracks_csv/56aba03ae4b058e549400f58.csv
envirocar_tracks_csv/56af2fb3e4b058e54940a022.csv
envirocar_tracks_csv/56af2fb6e4b058e54940a0c2.csv
envirocar_tracks_csv/56b21ceae4b0df8fa004b85c.csv
envirocar_tracks_csv/56b21cede4b0df8fa004baee.csv
envirocar_tracks_csv/56b3170de4b0df8fa0057314.csv
envirocar_tracks_csv/56b318e8e4b0df8fa0057d11.csv
envirocar_tracks_csv/56b326c0e4b0df8fa0058105.csv
envirocar_tracks_csv/56b3664fe4b0df8fa0059a88.csv
envirocar_tracks_csv/56b464a2e4b0df8fa005c794.csv
envirocar_tracks_csv/56b4dd7de4b0df8fa00669aa.csv
envirocar_tracks_csv/56bac74de4b0df8fa00ce240.csv
envirocar_tracks_csv/56bac770e4b0df8fa00ce53a.csv
envirocar_tracks_csv/56bac783e4b0df8fa00ce62a.csv
envirocar_tracks_csv/56bac799e4b0df8fa00ce8f1.csv
envirocar_tracks_csv/56bac7a9e4b0df8fa00cebe2.csv
envirocar_tracks_csv/56bac7e1e4b0df8fa00cf25a.csv
envirocar_tracks_csv/56bac7f3e4b0df8fa00cf3ef.csv
envirocar_tracks_csv/56bac805e4b0df8fa00cf584.csv
envirocar_tracks_csv/56bbae8ae4b0df8fa021e284.csv
envirocar_tracks_csv/56bbae8ce4b0df8fa021e387.csv
envirocar_tracks_csv/56bc4d14e4b0df8fa02aa6ce.csv
envirocar_tracks_csv/56bc4d15e4b0df8fa02aa852.csv
envirocar_tracks_csv/56bc4d17e4b0df8fa02aa895.csv
envirocar_tracks_csv/56c22080e4b0df8fa05006da.csv
envirocar_tracks_csv/56c4766fe4b0df8fa0524f2f.csv
envirocar_tracks_csv/56cc45cde4b0df8fa05e6c7b.csv
envirocar_tracks_csv/56ccef77e4b0df8fa05ed403.csv
envirocar_tracks_csv/56d4082de4b0df8fa0697f57.csv
envirocar_tracks_csv/56d4084be4b0df8fa06981e0.csv
envirocar_tracks_csv/56d408b4e4b0df8fa0698a31.csv
envirocar_tracks_csv/56e17859e4b0b5e237c1af13.csv
envirocar_tracks_csv/56ee65abe4b0b5e237d32e7f.csv
envirocar_tracks_csv/56f120ede4b0b5e237d5756f.csv
envirocar_tracks_csv/57057648e4b0b5e237edab37.csv
envirocar_tracks_csv/5705764be4b0b5e237edac7f.csv
envirocar_tracks_csv/5705764ee4b0b5e237edae2a.csv
envirocar_tracks_csv/5730c704e4b09078f95e7a68.csv
envirocar_tracks_csv/5730c739e4b09078f95e7cab.csv
envirocar_tracks_csv/57337c7fe4b09078f961f02b.csv
envirocar_tracks_csv/5734b29de4b09078f9624745.csv
envirocar_tracks_csv/573569e3e4b09078f96288e5.csv

In [16]:
df = pd.read_csv('envirocar_tracks_csv/5a2c14ea268d1b08cd0c1e79.csv')
new_df = df.fillna(df.median())
new_df

/tmp/ipykernel_30369/523925405.py:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  new_df = df.fillna(df.median())

,id,CO2(kg/h),GPS Bearing(deg),GPS HDOP(precision),GPS Altitude(m),MAF(l/s),Consumption(l/h),Speed(km/h),GPS Speed(km/h),Rpm(u/min),Throttle Position(%),GPS VDOP(precision),GPS PDOP(precision),GPS Accuracy(%),Intake Temperature(c),Engine Load(%),longitude,latitude,time
0,5a2c14ea268d1b08cd0c1e7b,3.298562,191.635529,1.0,102.068088,4.270000,1.403643,8.0,16.924856,1016.0,11.0,1.4,1.7,4.0,18.0,22.745098,7.687975,51.928315,2017-12-09T15:32:29Z
1,5a2c14ea268d1b08cd0c1e7d,10.977181,192.722961,0.8,102.065984,14.210000,4.671141,3.0,8.166852,1008.0,50.0,1.1,1.4,4.0,18.0,22.745098,7.687965,51.928280,2017-12-09T15:32:31Z
2,5a2c14ea268d1b08cd0c1e7e,2.595590,204.694290,0.8,102.071159,3.360000,1.104506,17.0,6.764933,1892.0,11.0,1.2,1.4,4.0,18.0,83.529411,7.687964,51.928277,2017-12-09T15:32:32Z
3,5a2c14ea268d1b08cd0c1e7f,13.410547,259.146362,0.8,101.771852,17.360001,5.706616,20.0,12.972728,1008.0,11.0,1.1,1.4,3.0,18.0,22.745098,7.687874,51.928233,2017-12-09T15:32:34Z
4,5a2c14ea268d1b08cd0c1e80,2.595590,274.166565,1.0,101.429505,3.360000,1.104506,26.0,18.454363,1816.0,67.0,1.3,1.7,3.0,32.0,80.392159,7.687786,51.928227,2017-12-09T15:32:35Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,5a2c14ea268d1b08cd0c219c,2.595590,8.457144,0.9,103.774900,3.360000,1.104506,38.0,35.074436,1795.0,11.0,1.3,1.6,3.0,38.0,22.745098,7.656026,51.968628,2017-12-09T15:54:18Z
801,5a2c14ea268d1b08cd0c219d,13.356472,9.442290,0.9,103.797562,17.290001,5.683605,40.0,40.164318,1008.0,38.0,1.3,1.6,4.0,38.0,22.745098,7.656087,51.968833,2017-12-09T15:54:20Z
802,5a2c14ea268d1b08cd0c219e,2.595590,11.389417,1.0,103.820528,3.360000,1.104506,45.0,42.040634,1641.0,11.0,1.5,1.8,4.0,32.0,80.000000,7.656119,51.968942,2017-12-09T15:54:21Z
803,5a2c14ea268d1b08cd0c219f,2.108917,11.465038,0.9,103.851947,2.730000,0.897411,45.0,45.577579,1233.0,11.0,1.5,1.8,4.0,38.0,22.745098,7.656195,51.969171,2017-12-09T15:54:23Z
804,5a2c14ea268d1b08cd0c21a0,2.595590,12.202407,1.0,103.890360,3.360000,1.104506,41.0,44.487732,865.0,11.0,1.5,1.8,4.0,32.0,20.000000,7.656235,51.969282,2017-12-09T15:54:25Z

In [17]:
df

,id,CO2(kg/h),GPS Bearing(deg),GPS HDOP(precision),GPS Altitude(m),MAF(l/s),Consumption(l/h),Speed(km/h),GPS Speed(km/h),Rpm(u/min),Throttle Position(%),GPS VDOP(precision),GPS PDOP(precision),GPS Accuracy(%),Intake Temperature(c),Engine Load(%),longitude,latitude,time
0,5a2c14ea268d1b08cd0c1e7b,3.298562,191.635529,1.0,102.068088,4.270000,1.403643,8.0,16.924856,1016.0,NaN,1.4,1.7,4.0,18.0,NaN,7.687975,51.928315,2017-12-09T15:32:29Z
1,5a2c14ea268d1b08cd0c1e7d,10.977181,192.722961,0.8,102.065984,14.210000,4.671141,3.0,8.166852,NaN,50.0,1.1,1.4,4.0,18.0,NaN,7.687965,51.928280,2017-12-09T15:32:31Z
2,5a2c14ea268d1b08cd0c1e7e,NaN,204.694290,0.8,102.071159,NaN,NaN,17.0,6.764933,1892.0,NaN,1.2,1.4,4.0,18.0,83.529411,7.687964,51.928277,2017-12-09T15:32:32Z
3,5a2c14ea268d1b08cd0c1e7f,13.410547,259.146362,0.8,101.771852,17.360001,5.706616,20.0,12.972728,NaN,NaN,1.1,1.4,3.0,18.0,NaN,7.687874,51.928233,2017-12-09T15:32:34Z
4,5a2c14ea268d1b08cd0c1e80,NaN,274.166565,1.0,101.429505,NaN,NaN,26.0,18.454363,1816.0,67.0,1.3,1.7,3.0,NaN,80.392159,7.687786,51.928227,2017-12-09T15:32:35Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,5a2c14ea268d1b08cd0c219c,NaN,8.457144,0.9,103.774900,NaN,NaN,38.0,35.074436,1795.0,NaN,1.3,1.6,3.0,38.0,NaN,7.656026,51.968628,2017-12-09T15:54:18Z
801,5a2c14ea268d1b08cd0c219d,13.356472,9.442290,0.9,103.797562,17.290001,5.683605,40.0,40.164318,NaN,38.0,1.3,1.6,4.0,38.0,NaN,7.656087,51.968833,2017-12-09T15:54:20Z
802,5a2c14ea268d1b08cd0c219e,NaN,11.389417,1.0,103.820528,NaN,NaN,45.0,42.040634,1641.0,NaN,1.5,1.8,4.0,NaN,80.000000,7.656119,51.968942,2017-12-09T15:54:21Z
803,5a2c14ea268d1b08cd0c219f,2.108917,11.465038,0.9,103.851947,2.730000,0.897411,45.0,45.577579,1233.0,NaN,1.5,1.8,4.0,38.0,NaN,7.656195,51.969171,2017-12-09T15:54:23Z
804,5a2c14ea268d1b08cd0c21a0,NaN,12.202407,1.0,103.890360,NaN,NaN,41.0,44.487732,865.0,11.0,1.5,1.8,4.0,NaN,20.000000,7.656235,51.969282,2017-12-09T15:54:25Z

In [19]:
import constants
import pandas as pd
da = None
for a in constants.all_columns_present_id_list[:3]:
    print(a)
    df = pd.read_csv("imputed_envirocar_data"+'/'+a+'.csv')
    da = df[df.columns[1:-1]]
# da
corr_matrix = da.corr()
corr_matrix['Calculated MAF(g/s)']
# corr_matrix[corr_matrix['CO2(kg/h)'] > 0.5]['CO2(kg/h)'].keys()

661245119828af15e2717fed
6612450a9828af15e2717c76
660b61e09828af15e232d0c3

CO2(kg/h)                         1.000000
GPS Altitude(m)                   0.172229
GPS Bearing(deg)                 -0.046275
GPS HDOP(precision)              -0.190669
Consumption(l/h)                  1.000000
Maximum Acceleration(m/s²)        0.872494
Speed(km/h)                       0.512930
Minimum Acceleration(m/s²)        0.872494
GPS Speed(km/h)                   0.494858
Rpm(u/min)                        0.917177
Minimum GPS Acceleration(m/s²)    0.635608
Throttle Position(%)              0.900215
GPS VDOP(precision)              -0.137816
CO2 Emission (GPS-based)(kg/h)         NaN
Intake Pressure(kPa)              0.924287
GPS PDOP(precision)              -0.152345
GPS Accuracy(%)                   0.138911
Intake Temperature(c)            -0.363431
Calculated MAF(g/s)               1.000000
Consumption (GPS-based)(l/h)           NaN
Maximum GPS Acceleration(m/s²)    0.635452
Engine Load(%)                    0.837955
longitude                        -0.259949
latitude                          0.269240
Name: Calculated MAF(g/s), dtype: float64